### ISSUE TITLE
failed to load config from /Users/hkshar/mywork/amazon-location-samples/mymap/amazon-location-features-demo-web/vite.config.ts

### ISSUE THREAD

**Issue by waytoharish** [aws-geospatial/amazon-location-features-demo-web#115]
Facing below issue while trying to run the application on my local system with nodev20x

hkshar@bcd0747fbd45 amazon-location-features-demo-web % npm run dev

> amazon-location-features-demo-web@0.0.0 dev
> vite

failed to load config from /Users/hkshar/mywork/amazon-location-samples/mymap/amazon-location-features-demo-web/vite.config.ts
error when starting dev server:
Error:
You installed esbuild for another platform than the one you're currently using.
This won't work because esbuild is written with native code and needs to
install a platform-specific binary executable.

Specifically the "esbuild-darwin-64" package is present but this platform
needs the "esbuild-darwin-arm64" package instead. People often get into this
situation by installing esbuild with npm running inside of Rosetta 2 and then
trying to use it with node running outside of Rosetta 2, or vice versa (Rosetta
2 is Apple's on-the-fly x86_64-to-arm64 translation service).

If you are installing with npm, you can try ensuring that both npm and node are
not running under Rosetta 2 and then reinstalling esbuild. This likely involves
changing how you installed npm and/or node. For example, installing node with
the universal installer here should work: https://nodejs.org/en/download/. Or
you could consider using yarn instead of npm which has built-in support for
installing a package on multiple platforms simultaneously.

If you are installing with yarn, you can try listing both "arm64" and "x64"
in your ".yarnrc.yml" file using the "supportedArchitectures" feature:
https://yarnpkg.com/configuration/yarnrc/#supportedArchitectures
Keep in mind that this means multiple copies of esbuild will be present.

Another alternative is to use the "esbuild-wasm" package instead, which works
the same way on all platforms. But it comes with a heavy performance cost and
can sometimes be 10x slower than the "esbuild" package, so you may also not
want to do that.

    at generateBinPath (/Users/hkshar/mywork/amazon-location-samples/mymap/amazon-location-features-demo-web/node_modules/esbuild/lib/main.js:1808:17)
    at esbuildCommandAndArgs (/Users/hkshar/mywork/amazon-location-samples/mymap/amazon-location-features-demo-web/node_modules/esbuild/lib/main.js:1886:33)
    at ensureServiceIsRunning (/Users/hkshar/mywork/amazon-location-samples/mymap/amazon-location-features-demo-web/node_modules/esbuild/lib/main.js:2051:25)
    at build (/Users/hkshar/mywork/amazon-location-samples/mymap/amazon-location-features-demo-web/node_modules/esbuild/lib/main.js:1942:26)
    at bundleConfigFile (file:///Users/hkshar/mywork/amazon-location-samples/mymap/amazon-location-features-demo-web/node_modules/vite/dist/node/chunks/dep-2faf2534.js:63043:26)
    at loadConfigFromFile (file:///Users/hkshar/mywork/amazon-location-samples/mymap/amazon-location-features-demo-web/node_modules/vite/dist/node/chunks/dep-2faf2534.js:63019:31)
    at resolveConfig (file:///Users/hkshar/mywork/amazon-location-samples/mymap/amazon-location-features-demo-web/node_modules/vite/dist/node/chunks/dep-2faf2534.js:62643:34)
    at createServer (file:///Users/hkshar/mywork/amazon-location-samples/mymap/amazon-location-features-demo-web/node_modules/vite/dist/node/chunks/dep-2faf2534.js:61943:26)
    at CAC.<anonymous> (file:///Users/hkshar/mywork/amazon-location-samples/mymap/amazon-location-features-demo-web/node_modules/vite/dist/node/cli.js:707:30)

**Comment by neelmurt** [comment]
Hey, just wanted to check in on this issue. Did the suggestion above end up working as a fix?

**Comment by its-aazizi** [comment]
Hello @waytoharish , Can you elaborate a bit on STR? Haven't been able to reproduce this.

**Comment by its-aazizi** [comment]
Hello @neelmurt @waytoharish @mbalfour-amzn, can we close this issue?

**Comment by waytoharish** [comment]
Yes Please
